debug: false

Card2kAPI:
  key: '' #partner id ủa bnaj từ card2k.com
  secret: '' #partner key của bạn từ card2k.com
# Thời gian chờ trước khi kiểm tra trạng thái thẻ lần đầu (tính bằng phút)
delay_before_reward: 2

# Số lần kiểm tra lại nếu status vẫn là 99 (0 = không kiểm tra lại)
max_retry: 1

# Thời gian mà placeholder cập nhật, tính theo tick (20 tick = 1s)
placeholder_update: 300

# Bật tính năng nạp thẻ nhanh bằng lệnh
fastcmd: true

# Chấp nhận nạp các loại thẻ được liệt kê bên dưới
card:
  enable:
    - Viettel
    - Vinaphone
    - Vietnamobile
    - Mobifone
    - Gate
    - Garena
    - Vcoin
    - Zing

  # Thực hiện các lệnh khi nạp thành công các thẻ có mệnh giá tương đương
  command:
    10000:
      - 'console:points give {player} 10'
      - 'console:broadcast {player} vừa ủng hộ 10k!'
      - 'me vừa ủng hộ server 10k!'
    20000:
      - 'console:points give {player} 20'
      - 'console:broadcast {player} vừa ủng hộ 20k!'
      - 'me vừa ủng hộ server 20k!'
    30000:
      - 'console:points give {player} 30'
      - 'console:broadcast {player} vừa ủng hộ 30k!'
      - 'me vừa ủng hộ server 30k!'
    50000:
      - 'console:points give {player} 50'
      - 'console:broadcast {player} vừa ủng hộ 50k!'
      - 'me vừa ủng hộ server 50k!'
    100000:
      - 'console:points give {player} 100'
      - 'console:broadcast {player} vừa ủng hộ 100k!'
      - 'me vừa ủng hộ server 100k!'
    200000:
      - 'console:points give {player} 200'
      - 'console:broadcast {player} vừa ủng hộ 200k!'
      - 'me vừa ủng hộ server 200k!'
    300000:
      - 'console:points give {player} 300'
      - 'console:broadcast {player} vừa ủng hộ 300k!'
      - 'me vừa ủng hộ server 300k!'
    500000:
      - 'console:points give {player} 500'
      - 'console:broadcast {player} vừa ủng hộ 500k!'
      - 'me vừa ủng hộ server 500k!'
    1000000:
      - 'console:points give {player} 1000'
      - 'console:broadcast {player} vừa ủng hộ 1 triệu!'
      - 'me vừa ủng hộ server 1tr!'

# Tính năng tặng quà cho người theo các các mốc nạp

# Thực hiện các lệnh khi đạt mốc tổng nạp
milestones:
  enable: true
  command:
    10000:
      - 'console:broadcast {player} đạt mốc nạp 10k!'
    20000:
      - 'console:broadcast {player} đạt mốc nạp 20k!'
    30000:
      - 'console:broadcast {player} đạt mốc nạp 30k!'
    50000:
      - 'console:broadcast {player} đạt mốc nạp 50k!'
    100000:
      - 'console:broadcast {player} đạt mốc nạp 100k!'
    200000:
      - 'console:broadcast {player} đạt mốc nạp 200k!'
    300000:
      - 'console:broadcast {player} đạt mốc nạp 300k!'
    500000:
      - 'console:broadcast {player} đạt mốc nạp 500k!'
    1000000:
      - 'console:broadcast {player} đạt mốc nạp 1tr!'
